image: docker:latest

services:
- docker:dind

before_script:
- ip a s
- apk add --update bash
- docker version
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"



build-all:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE"/chicken-and-egg
    - docker push "$CI_REGISTRY_IMAGE"/chicken-and-egg
    - singularity/build.sh
  artifacts:
    paths:
      - singularity/chicken-and-egg.img
  only:
    - master
