image: docker

services:
- docker:dind

build-all:
  stage: build
  script:
    - apt update
    - apt install -y ca-certificates docker.io smbclient
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - smbget -U "$SMB_USER%$SMB_PASSWORD" $SMB_SHARE/$INTELPYTHON
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
