image: ubuntu:latest

#services:
#- docker:dind
#

before_script:
  - apt update
  - apt install -y singularity-container ca-certificates docker.io
  - dockerd &
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY



build-all:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - SINGULARITY_DOCKER_USERNAME=$CI_REGISTRY_USER SINGULARITY_DOCKER_PASSWORD=$CI_REGISTRY_PASSWORD singularity build -w singularity/chicken-and-egg.img docker://$CI_REGISTRY_IMAGE
  artifacts:
    paths:
      - singularity/chicken-and-egg.img 
  only:
    - master
