image: ubuntu:latest

#services:
#- docker:dind

before_script:
  - apt update
  - apt install -y singularity-container



build-all:
  stage: build
  script:
    - SINGULARITY_DOCKER_USERNAME=$CI_REGISTRY_USER SINGULARITY_DOCKER_PASSWORD=$CI_REGISTRY_PASSWORD singularity build -w singularity/chicken-and-egg.img docker://$CI_REGISTRY_IMAGE/chicken-and-egg
  artifacts:
    paths:
      - singularity/chicken-and-egg.img 
  only:
    - master
