apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: system-default
  apiGroup: rbac.authorization.k8s.io
