apiVersion: v1
kind: PersistentVolumeClaim
metadata:                                                                       
  name: chicken-work
spec:                                                                           
  accessModes:                                                                  
    - ReadWriteMany                                                             
  resources:                                                                    
    requests:                                                                   
      storage: 20Gi                                                              
  storageClassName: csi-nfs
